[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = [
    "tests"
]
[tool.black]
line-length = 88
target-version = ['py311']
exclude = '''
/(
    \.venv
  | __pycache__
  | \.git
)/
'''
